### ISSUE TITLE
Issue with Binary Files

### ISSUE THREAD

**Issue by nerd-deus** [nerd-deus/GPA-calculator#1]
`void test::add_details(){
	fstream db;
	db.open("test_case.dat", ios::out | ios::app | ios::binary);
	if(db.is_open()){ 
        cout<<"OPEN..."; 
        }
	db.write( ( char* )&c1, sizeof( test ) );
	db.close();
}`
Data is not being stored as it is supposed to be.
 There are two data types being store- int and string. 
Input: 40
          < any name >
File: 
         (           < any name >

This is what is being stored in the dat file.
@MFReaper

**Comment by nerd-deus** [comment]
check this:
GPA-calculator/test_2_files_and_class.cpp

**Comment by MFReaper** [comment]
the data was being stored, its the check which was wrong

**Comment by nerd-deus** [comment]
Fixed #1

**Comment by nerd-deus** [comment]
Fixed #1

**Comment by nerd-deus** [comment]
@Yash-Garg

**Comment by Yash-Garg** [comment]
@nerd-deus It works!

**Comment by Yash-Garg** [comment]
@nerd-deus @MFReaper TESTING NOTIFICATION !!!!

**Comment by nerd-deus** [comment]
nice works perfectly

**Comment by nerd-deus** [comment]
line no. 102, 115, 162 and 175: beginning of the functions you need to check

**Comment by nerd-deus** [comment]
the `show_details()` function was running 1 extra tieme when i was running it with the `while` loop so i switched to `for` but still the same problem, I guess the data stream to/from file is in the same order,
the `for` loop runs one extra time IDKY.
@MFReaper

**Comment by MFReaper** [comment]
What is the issue exactly? Just this? and open new issues for different bugs man
@nerd-deus
:laugh:

**Comment by nerd-deus** [comment]
i guess it was issue with binary files only so i reopened it 
wait i'll create another issue.
* feels like an over-dramatic girl * flashbacks * *
@MFReaper

**Comment by MFReaper** [comment]
Here's the code:

````
void std_details::show_details(){
	ifstream s_data;
	s_data.open("Files/data.dat", ios::in | ios::binary);
	for( int i=0 ; i < n_types ; i++ ) {	//reading the data from the file
		s_data.read( (char*)&sr_det, sizeof(std_details) );
		//the data is now saved in sr_det automatically
		cout << "ID: " << sr_det.ID << endl;	
		cout << "Name: " << sr_det.name << endl;
		cout << "Class: " << sr_det.s_class << endl;
		cout << "Section: " << sr_det.sec << endl;
	}
	s_data.close();
	return;	
}
````

compiler says n_types not declared!!
@nerd-deus
