### ISSUE TITLE
check_config() function returns some arbitrary value 

### ISSUE THREAD

**Issue by nerd-deus** [nerd-deus/GPA-calculator#3]
check main.cpp in edit_main branch
@MFReaper

**Comment by MFReaper** [comment]
Check_config is declared void

**Comment by nerd-deus** [comment]
How does that affect it anyway?
@MFReaper

**Comment by MFReaper** [comment]
You can't use it to return a value

**Comment by nerd-deus** [comment]
check_config() is not returning any value

**Comment by MFReaper** [comment]
Your issue is that it returns an arbitrary value

**Comment by nerd-deus** [comment]
according to code it should work

**Comment by MFReaper** [comment]
Can see the file you are opening

**Comment by MFReaper** [comment]
Upload that too

**Comment by nerd-deus** [comment]
check it: GPA-calculator/config.txt

**Comment by MFReaper** [comment]
String variable range in not initialized with a value...it has random value
1. probably initialize it as empty string. Try next if this doesn't work
2. maybe change the += to absolute position _suggested_
  - ` range[k-j-1] = word[k]`

**Comment by nerd-deus** [comment]
`string range='\0';`
`while ( word[k] != ']' ){`
								`range[k-j-1] = word[k];`
								`k++;`
							`}`

did this

**Comment by MFReaper** [comment]
Found error!!!
Line 128, change condition
````
While( cfg.getline( word, 30) ) {
.
.
.
}
````

**Comment by nerd-deus** [comment]
Perfect. But now the output i get to test if the data is being stored is 0 : 0

`cout<<n_fa<<" : "<<n_gpa;`

**Comment by nerd-deus** [comment]
Strange enough, the while loops works perfectly but nothing is being copied in the variable word.

**Comment by MFReaper** [comment]
Line 138:
````
cfg.seekg( - ( sizeof( char ) * strlen( word ) );
````

_PS: Sorry don't have PC so can't test before sending_

**Comment by Yash-Garg** [comment]
Cool !!
