### ISSUE TITLE
Binary file i/o

### ISSUE THREAD

**Issue by nerd-deus** [nerd-deus/GPA-calculator#5]
line no. 102, 115, 162 and 175: beginning of the functions you need to check

the show_details() function was running 1 extra tieme when i was running it with the while loop so i switched to for but still the same problem, I guess the data stream to/from file is in the same order,
the for loop runs one extra time IDKY.
@MFReaper

**Comment by nerd-deus** [comment]
line no. 102, 115, 162 and 175: beginning of the functions you need to check

the show_details() function was running 1 extra tieme when i was running it with the while loop so i switched to for but still the same problem, I guess the data stream to/from file is in the same order,
the for loop runs one extra time IDKY.
@MFReaper

**Comment by MFReaper** [comment]
line 28:

`
} sw_det, sr_det, sr_marks;
`

Line 118:

````
	while ( s_data.read( (char*)&sr_det, sizeof( std_details ) ) ) {	//reading the data from the file
		//the data is now saved in sr_det automatically
		cout << "ID: " << sr_det.ID << endl;	
		cout << "Name: " << sr_det.name << endl;
		cout << "Class: " << sr_det.s_class << endl;
		cout << "Section: " << sr_det.sec << endl;
	}
````

Line 177:

````
	while(s_data.read( (char*)&sr_marks, sizeof( std_marks ) ) ) {	//reading the data from the file
		//the data is now saved in sr_mks automatically
		cout<< "Marks:- \n";
		for(int i=0 ; i < n_sub ; i++){
			cout<< "\tSubject " << i <<	": " << marks[i];
			cout<<endl;
		}
		cout<< "Percentage:- \n";
		for(int i=0 ; i < n_sub ; i++){
			cout<<"\tSubject "<< i << ": " << sr_mks.perc[i];
			cout<<endl;
		}
		cout<< "GPA:- \n";
		for(int i=0 ; i < n_sub ; i++){
			cout<<"\tSubject "<< i << ": " << sr_mks.gpa[i];
			cout<<endl;
		}
		cout<< "CGPA: " << sr_mks.cgpa;
		cout<<endl;
	}
````

@nerd-deus this fixes the i/o errors.

I think u may have issues in the assign_id() function because the program crashes around that part

Open another issue of that's the case..
My net shit so not forking and merge request and stuff

:boom:

**Comment by MFReaper** [comment]
Dude you have a major error.
You have output 2 different types types of classes in the same file

__YOU CAN'T DO THAT SHIT__

😱 😱 😱

**Comment by nerd-deus** [comment]
dude, the `assign ID()` function if working perfectly.

**Comment by nerd-deus** [comment]
BTW @MFReaper 
why did you declare `sr_marks` for line 177?
It wasn't needed ig, check the test_program, i kept the same read pattern here as was in the test_program...
